(deftheme moe-dark-template
  "Created 2020-03-08.")

(custom-theme-set-variables
 'moe-dark-template
 '(ansi-color-names-vector ["#303030" "#ff4b4b" "#d7ff5f" "#fce94f" "#5fafd7" "#d18aff" "#afd7ff" "#c6c6c6"]))

(custom-theme-set-faces
 'moe-dark-template
 '(cursor ((((class color) (min-colors 89)) (:background "#eeeeee"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#a8a8a8" :background "#4e4e4e"))))
 '(line-number ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#4e4e4e"))))
 '(line-number-current-line ((((class color) (min-colors 89)) (:background "#d7ff5f" :foreground "#3a3a3a"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#4e4e4e"))))
 '(region ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#d7ff5f"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#005f87" :foreground "#eeeeee"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#ff5d17"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#ff1f8b" :foreground "#c6c6c6"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#a40000"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#005f87" :foreground nil))))
 '(header-line ((((class color) (min-colors 89)) (:background "#005f87" :foreground "#eeeeee"))))
 '(help-argument-name ((((class color) (min-colors 89)) (:foreground "#ff7bbb" :italic t))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#d7ff00" :bold t :underline t :background "#005f00"))))
 '(mode-line ((((class color) (min-colors 89)) (:box nil :background "#afd7ff" :foreground "#005f87"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box nil :background "#6c6c6c" :foreground "#c6c6c6"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:box nil :foreground "#303030" :background nil :bold t))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#4e4e4e"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#a1db00"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#c4a000"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#ff4b4b"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#ffaf5f"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#afff00"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#d18aff"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#6c6c6c" :slant italic))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#6c6c6c" :slant italic))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#ff4b4b"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#ffd700"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#ff4b4b"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#d18aff"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#fce94f"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#d18aff"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#00d7af"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#dd0000"))))
 '(completions-annotations ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(completions-common-part ((((class color) (min-colors 89)) (:foreground "#6c6c6c"))))
 '(completions-first-difference ((((class color) (min-colors 89)) (:weight bold :foreground "#ff8700"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#afd7ff" :background "#303030" :weight bold))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#303030" :weight bold))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#ffaf5f" :background "#6c6c6c"))))
 '(org-archived ((((class color) (min-colors 89)) (:slant italic))))
 '(org-checkbox ((((class color) (min-colors 89)) (:background "#c6c6c6" :foreground "#4e4e4e" :box (:line-width 1 :style released-button)))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#afd7ff" :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:bold t :weight bold :foreground "#008700" :background "#d7ff5f" :box (:line-width 1 :style none)))))
 '(org-todo ((((class color) (min-colors 89)) (:bold t :weight bold :foreground "#a40000" :background "#ffaf87" :box (:line-width 1 :style none)))))
 '(org-level-1 ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(org-level-2 ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:foreground "#00d7af"))))
 '(org-level-5 ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:foreground "#ffd700"))))
 '(org-tag ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#c6c6c6" :bold t :weight bold))))
 '(org-column ((((class color) (min-colors 89)) (:background "#3a3a3a" :foreground "#4e4e4e"))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#afd7ff" :foreground "#303030" :underline t :weight bold))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#00ac8a" :background nil :bold t))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#c6c6c6"))))
 '(org-table ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#c6c6c6"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(org-warning ((((class color) (min-colors 89)) (:bold t :foreground "#eeeeee" :background "#a40000"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#303030"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#3a3a3a"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#5fafd7" :underline t))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#ff1f8b"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#dd0000"))))
 '(org-agenda-clocking ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff" :bold t))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#303030" :underline nil))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:foreground "#d18aff" :underline nil :bold nil))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:foreground "#afd7ff" :background "#6c6c6c" :slant italic :weight bold))))
 '(org-agenda-column-dateline ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#4e4e4e" :underline t))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#a1db00" :background nil))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#dd0000"))))
 '(org-priority ((((class color) (min-colors 89)) (:foreground "#ef2929" :background nil))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#3a3a3a"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#005f87"))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#3a3a3a"))))
 '(org-quote ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#4e4e4e"))))
 '(org-mode-line-clock ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff" :bold t))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#ef2929" :bold t))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#4e4e4e" :bold nil))))
 '(outline-1 ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(outline-2 ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(outline-3 ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(outline-4 ((((class color) (min-colors 89)) (:foreground "#00d7af"))))
 '(outline-5 ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(outline-6 ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(outline-7 ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(outline-8 ((((class color) (min-colors 89)) (:foreground "#ffd700"))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#c6c6c6"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#a1db00" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#dd0000"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#ffd700"))))
 '(markdown-blockquote-face ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#4e4e4e" :italic t))))
 '(markdown-bold-face ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :bold t))))
 '(markdown-comment-face ((((class color) (min-colors 89)) (:foreground "#8a8a8a" :italic t))))
 '(markdown-header-delimiter-face ((((class color) (min-colors 89)) (:foreground "#5faf00" :bold t))))
 '(markdown-header-face ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(markdown-header-rule-face ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(markdown-header-face-1 ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(markdown-header-face-2 ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(markdown-header-face-3 ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(markdown-header-face-4 ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(markdown-header-face-5 ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(markdown-header-face-6 ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(markdown-link-face ((((class color) (min-colors 89)) (:foreground "#ff7bbb" :underline t))))
 '(markdown-inline-code-face ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#4e4e4e"))))
 '(markdown-italic-face ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :italic t :underline "#c6c6c6"))))
 '(markdown-list-face ((((class color) (min-colors 89)) (:foreground "#a1db00" :background "#303030" :bold t))))
 '(markdown-math-face ((((class color) (min-colors 89)) (:foreground "#ff7bbb"))))
 '(markdown-missing-link-face ((((class color) (min-colors 89)) (:foreground "#ef2929" :bold t))))
 '(markdown-pre-face ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(markdown-reference-face ((((class color) (min-colors 89)) (:foreground "#ff8700" :italic t))))
 '(markdown-url-face ((((class color) (min-colors 89)) (:foreground "#ff1f8b" :underline "#ff1f8b"))))
 '(company-echo ((((class color) (min-colors 89)) (:background nil :foreground "#c6c6c6"))))
 '(company-echo-common ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#ef2929"))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#303030" :foreground "#ff4ea3"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:background "#303030" :foreground "#ff4ea3"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:background "#3a3a3a" :foreground "#ff4ea3" :bold t))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#4e4e4e"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#b2b2b2"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#5fafd7"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:background "#3a3a3a" :foreground "#ef2929"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:background "#6c6c6c" :foreground "#afd7ff"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:background "#005f87" :foreground "#afd7ff" :bold t))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:background "#d7ff5f" :foreground "#303030"))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#005f87" :foreground "#afd7ff"))))
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "#5fafd7"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#1f5bff"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#c4a000"))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:foreground "#00d7af"))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(gnus-group-news-6 ((((class color) (min-colors 89)) (:foreground "#afff00"))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:foreground "#c4a000"))))
 '(gnus-group-news-low-empty ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(gnus-splash ((((class color) (min-colors 89)) (:foreground "#a8a8a8"))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:foreground "#8a8a8a" :background "#303030"))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 89)) (:bold t :foreground "#a40000" :background nil))))
 '(gnus-summary-high-read ((((class color) (min-colors 89)) (:bold t :foreground "#c6c6c6"))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 89)) (:slant italic :bold t :foreground "#dd0000" :background nil))))
 '(gnus-summary-high-undownloaded ((((class color) (min-colors 89)) (:slant italic :foreground "#dd0000" :background nil))))
 '(gnus-summary-high-unread ((((class color) (min-colors 89)) (:bold t :foreground "#ff4b4b"))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 89)) (:foreground "#5faf00"))))
 '(gnus-summary-low-read ((((class color) (min-colors 89)) (:foreground "#c6c6c6"))))
 '(gnus-summary-low-ticked ((((class color) (min-colors 89)) (:slant italic :foreground "#afff00"))))
 '(gnus-summary-low-undownloaded ((((class color) (min-colors 89)) (:slant italic :foreground "#a1db00"))))
 '(gnus-summary-low-unread ((((class color) (min-colors 89)) (:slant italic :foreground "#d7ff5f"))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 89)) (:foreground "#1f5bff"))))
 '(gnus-summary-normal-read ((((class color) (min-colors 89)) (:foreground "#c6c6c6"))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 89)) (:slant italic :foreground "#5fafd7"))))
 '(gnus-summary-normal-undownloaded ((((class color) (min-colors 89)) (:slant italic :foreground "#5fafd7"))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 89)) (:foreground "#afd7ff" :bold t))))
 '(gnus-summary-selected ((((class color) (min-colors 89)) (:background "#d7ff5f" :foreground "#005f00"))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#5fafd7" :bold t))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#303030" :background "#a1db00" :bold t))))
 '(dired-ignored ((((class color) (min-colors 89)) (:foreground "#a8a8a8"))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#afff00"))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#dd0000" :bold t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#a40000" :bold t))))
 '(diredp-compressed-file-suffix ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(diredp-date-time ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#3a3a3a"))))
 '(diredp-deletion ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#a40000"))))
 '(diredp-deletion-file-name ((((class color) (min-colors 89)) (:foreground "#dd0000"))))
 '(diredp-dir-heading ((((class color) (min-colors 89)) (:foreground "#303030" :background "#a1db00"))))
 '(diredp-dir-priv ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#303030" :bold t))))
 '(diredp-executable-tag ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(diredp-file-name ((((class color) (min-colors 89)) (:foreground "#c6c6c6"))))
 '(diredp-file-suffix ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(diredp-flag-mark ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#ff1f8b" :bold t))))
 '(diredp-flag-mark-line ((((class color) (min-colors 89)) (:foreground "#303030" :background "#ff7bbb"))))
 '(diredp-ignored-file-name ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(diredp-link-priv ((((class color) (min-colors 89)) (:foreground "#ff1f8b"))))
 '(diredp-mode-line-flagged ((((class color) (min-colors 89)) (:foreground "#303030" :background "#a1db00"))))
 '(diredp-mode-line-marked ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#ff1f8b" bold t))))
 '(diredp-no-priv ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#3a3a3a"))))
 '(diredp-number ((((class color) (min-colors 89)) (:foreground "#fce94f"))))
 '(diredp-other-priv ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#005f87"))))
 '(diredp-rare-priv ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#af5fff"))))
 '(diredp-symlink ((((class color) (min-colors 89)) (:foreground "#ff1f8b"))))
 '(diredp-read-priv ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff5f"))))
 '(diredp-write-priv ((((class color) (min-colors 89)) (:foreground "#0000af" :background "#afd7ff"))))
 '(diredp-exec-priv ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ffaf87"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#d7ff5f" :background "#3a3a3a" :bold t))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#ffd700" :background "#3a3a3a" :bold t))))
 '(diff-context ((((class color) (min-colors 89)) (:foreground "#6c6c6c"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#303030" :background "#afd7ff" :bold t))))
 '(diff-function ((((class color) (min-colors 89)) (:foreground "#3a3a3a" :background "#c6c6c6"))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff"))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#afd7ff" :background "#4e4e4e" :bold t))))
 '(diff-index ((((class color) (min-colors 89)) (:foreground "#3a3a3a" :background "#b2b2b2" :bold t))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#5faf00" :bold t))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#c4a000" :bold t))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#a40000" :bold t))))
 '(diff-nonexistent ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#a40000" :bold t))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#008700" :bold t))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#a40000" :bold t))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#ff4b4b" :background "#3a3a3a" :bold t))))
 '(flyspell-duplicate ((((class color) (min-colors 89)) (:underline t foreground-color "#ffaf5f"))))
 '(flyspell-incorrect ((((class color) (min-colors 89)) (:background "#ef2929" :foreground "#c6c6c6" :bold t))))
 '(avy-lead-face ((((class color) (min-colors 89)) (:background "#87ffff" :foreground "#3a3a3a"))))
 '(avy-lead-face-0 ((((class color) (min-colors 89)) (:background "#e6a8df" :foreground "#3a3a3a"))))
 '(avy-lead-face-1 ((((class color) (min-colors 89)) (:background "#c6c6c6" :foreground "#3a3a3a"))))
 '(avy-lead-face-2 ((((class color) (min-colors 89)) (:background "#a1db00" :foreground "#3a3a3a"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:bold t :foreground "#dd0000"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:bold t :foreground "#5fafd7"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:bold t :foreground "#a1db00"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:bold t :foreground "#ff4ea3"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:bold t :foreground "#00d7af"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:bold t :foreground "#ff8700"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:bold t :foreground "#af5fff"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:bold t :foreground "#c6c6c6"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:bold t :foreground "#ffd700"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#a40000" :bold t))))
 '(comint-highlight-prompt ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#6c6c6c" :bold t))))
 '(flycheck-error ((((class color) (min-colors 89)) (:background "#dd0000" :foreground "#eeeeee" :bold t))))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#ff8700" :underline t))))
 '(js2-error ((((class color) (min-colors 89)) (:foreground "#dd0000" :underline t :bold t))))
 '(js2-warning ((((class color) (min-colors 89)) (:foreground nil :underline t :bold t))))
 '(rst-level-1 ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#303030" :bold t))))
 '(rst-level-2 ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#303030" :bold t))))
 '(rst-level-3 ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#303030" :bold t))))
 '(rst-level-4 ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#303030" :bold t))))
 '(rst-level-5 ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#303030" :bold t))))
 '(rst-level-6 ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#303030" :bold t))))
 '(rst-adornment ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#303030" :bold t))))
 '(rst-block ((((class color) (min-colors 89)) (:foreground "#afff00" :background "#4e4e4e" :bold t))))
 '(rst-comment ((((class color) (min-colors 89)) (:foreground "#ff4b4b" :background "#a40000" :bold t))))
 '(rst-literal ((((class color) (min-colors 89)) (:foreground "#afff00" :background "#4e4e4e"))))
 '(rst-reference ((((class color) (min-colors 89)) (:foreground "#ff4ea3" :background "#303030"))))
 '(rst-definition ((((class color) (min-colors 89)) (:foreground "#fce94f" :background "#303030"))))
 '(rst-directive ((((class color) (min-colors 89)) (:foreground "#d18aff" :background "#3a3a3a" :bold t))))
 '(rst-external ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#303030"))))
 '(rst-transition ((((class color) (min-colors 89)) (:foreground "#a1db00" :background "#3a3a3a" :bold t))))
 '(term-color-black ((((class color) (min-colors 89)) (:background "#303030" :foreground "#303030"))))
 '(term-color-blue ((((class color) (min-colors 89)) (:background "#00d7af" :foreground "#00d7af"))))
 '(term-color-cyan ((((class color) (min-colors 89)) (:background "#00d7af" :foreground "#00d7af"))))
 '(term-color-green ((((class color) (min-colors 89)) (:background "#a1db00" :foreground "#a1db00"))))
 '(term-color-magenta ((((class color) (min-colors 89)) (:background "#ff1f8b" :foreground "#ff1f8b"))))
 '(term-color-red ((((class color) (min-colors 89)) (:background "#ef2929" :foreground "#ef2929"))))
 '(term-color-white ((((class color) (min-colors 89)) (:background "#eeeeee" :foreground "#eeeeee"))))
 '(term-color-yellow ((((class color) (min-colors 89)) (:background "#ff8700" :foreground "#ff8700"))))
 '(ivy-current-match ((((class color) (min-colors 89)) (:foreground "#ff8700" :bold t :inherit highlight))))
 '(ivy-confirm-face ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff87" :bold t))))
 '(ivy-subdir ((((class color) (min-colors 89)) (:foreground "#5fafd7" :bold t))))
 '(ivy-virtual ((((class color) (min-colors 89)) (:foreground "#ff1f8b"))))
 '(ivy-minibuffer-match-face-1 ((((class color) (min-colors 89)) (:background "#5fafd7" :foreground "#eeeeee"))))
 '(ivy-minibuffer-match-face-2 ((((class color) (min-colors 89)) (:bold t :background "#a1db00" :foreground "#eeeeee"))))
 '(ivy-minibuffer-match-face-3 ((((class color) (min-colors 89)) (:bold t :background "#ff4ea3" :foreground "#eeeeee"))))
 '(ivy-minibuffer-match-face-4 ((((class color) (min-colors 89)) (:bold t :background "#00d7af" :foreground "#eeeeee"))))
 '(swiper-match-face-1 ((((class color) (min-colors 89)) (:background "#5fafd7" :foreground "#eeeeee"))))
 '(swiper-match-face-2 ((((class color) (min-colors 89)) (:bold t :background "#a1db00" :foreground "#eeeeee"))))
 '(swiper-match-face-3 ((((class color) (min-colors 89)) (:bold t :background "#ff4ea3" :foreground "#eeeeee"))))
 '(swiper-match-face-4 ((((class color) (min-colors 89)) (:bold t :background "#00d7af" :foreground "#eeeeee"))))
 '(swiper-line-face ((((class color) (min-colors 89)) (:foreground "#ff8700" :bold t :inherit highlight))))
 '(widget-button ((((class color) (min-colors 89)) (:foreground "#5fafd7" :underline t :bold t))))
 '(widget-button-pressed ((((class color) (min-colors 89)) (:foreground "#afd7ff"))))
 '(widget-documentation ((((class color) (min-colors 89)) (:foreground "#afff00"))))
 '(widget-field ((((class color) (min-colors 89)) (:foreground "#d7ff5f" :background "#4e4e4e"))))
 '(widget-inactive ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(widget-single-line-field ((((class color) (min-colors 89)) (:foreground "#d7ff5f" :background "#4e4e4e"))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(compilation-error ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ff4b4b" :bold t))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#4e4e4e"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff5f" :bold t))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ffafaf" :bold t))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#d75f00" :background "#ffd787" :bold t))))
 '(compilation-warning ((((class color) (min-colors 89)) (:foreground "#ff5d17"))))
 '(info-header-node ((((class color) (min-colors 89)) (:foreground "#ff4ea3" :bold t))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background nil :bold t))))
 '(info-index-match ((((class color) (min-colors 89)) (:background "#005f87"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:foreground "#eeeeee" :bold t :underline t))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#a40000"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:foreground "#5fafd7" :bold t))))
 '(info-title-2 ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(info-title-3 ((((class color) (min-colors 89)) (:foreground "#ff8700" :bold t))))
 '(info-title-4 ((((class color) (min-colors 89)) (:foreground "#ff4ea3" :bold t))))
 '(info-xref ((((class color) (min-colors 89)) (:foreground "#5fafd7" :underline t))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:foreground "#d18aff" :underline t))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#a8a8a8" :background "#4e4e4e"))))
 '(tty-menu-disabled-face ((((class color) (min-colors 89)) (:foreground "#6c6c6c" :background "#4e4e4e"))))
 '(tty-menu-enabled-face ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#4e4e4e" :bold t))))
 '(tty-menu-selected-face ((((class color) (min-colors 89)) (:background "#005f87"))))
 '(web-mode-comment-face ((((class color) (min-colors 89)) (:foreground "#6c6c6c"))))
 '(web-mode-current-element-highlight-face ((((class color) (min-colors 89)) (:background "#4e4e4e"))))
 '(web-mode-current-column-highlight-face ((((class color) (min-colors 89)) (:background "#4e4e4e"))))
 '(web-mode-symbol-face ((((class color) (min-colors 89)) (:foreground "#ffd700"))))
 '(web-mode-type-face ((((class color) (min-colors 89)) (:foreground "#00d7af"))))
 '(custom-button ((((class color) (min-colors 89)) (:background "#afd7ff" :foreground "#005f87" :box (:line-width 1 :style released-button)))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:background "#d7d7ff" :foreground "#4e4e4e" :box (:line-width 1 :style released-button)))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#c6c6c6" :box (:line-width 1 :style pressed-button)))))
 '(hydra-face-red ((((class color) (min-colors 89)) (:foreground "#ff4b4b"))))
 '(hydra-face-blue ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(hydra-face-amaranth ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(default ((((class color) (min-colors 4096)) (:foreground "#c6c6c6" :background "#303030")) (((class color) (min-colors 256)) (:foreground "#c6c6c6" :background "#303030")) (((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#303030")))))

(provide-theme 'moe-dark-template)
