;;; -*- lexical-binding: t; -*-

(straight-use-package 'org-bullets)
(straight-use-package 'deft)
(straight-use-package 'evil-org)
(straight-use-package 'helm-org)
(straight-use-package 'helm-org-rifle)
(straight-use-package 'org-projectile)
(straight-use-package 'org-sticky-header)
(straight-use-package 'org-mime)
(straight-use-package 'org-journal)
(straight-use-package 'ivy-omni-org)
(straight-use-package 'org-download)
(straight-use-package 'org-starter)
(straight-use-package 'org-starter-swiper)
